# Generated by Django 5.0.4 on 2024-06-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_remove_emprestimo_tempo_duracao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='Emprestimos',
        ),
    ]
