# Generated by Django 5.0.4 on 2024-06-07 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_alter_emprestimos_avaliacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_emprestado_anonimmo',
            new_name='nome_emprestado_anonimo',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 15, 38, 53, 668596)),
        ),
    ]
